version: "3.7"

services:
  backend:
    container_name: backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001" # remove after ngnx is set up
    restart: on-failure
    volumes:
      - /app/node_modules # don't override folder inside container
  mongo:
    image: "mongo"
    container_name: "mongo"
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./db/mongo-volume:/data/db
