version: "3.7"

services:
  mongo:
    image: "mongo:latest"
    container_name: "mongo"
    command: mongod --port ${MONGO_PROD_CONTAINER_PORT}
    ports:
      - ${MONGO_PROD_CONTAINER_PORT}:${MONGO_PROD_CONTAINER_PORT}
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongodb:/data/db
    networks:
      - network
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules # don't override folder inside container
    restart: on-failure
    networks:
      - network
  backend:
    container_name: backend
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - /app/node_modules # don't override folder inside container
    networks:
      - network
  nginx:
    container_name: nginx
    depends_on:
      - client
      - backend
    restart: always # routing traffic to entire app
    ports: 
      - 80:80
    build:
      context: ./nginx
      dockerfile: Dockerfile
    networks:
      - network
networks:
  network:
    name: ${DOCKER_PROD_NETWORK}
volumes:
  mongodb: