# base image
FROM node:12-alpine AS alpine

WORKDIR /app

# dependencies
COPY package.json .
RUN yarn install 
COPY . .

EXPOSE 3001

# run 'yarn run start:debug' when the container starts
CMD ["yarn", "run", "start:debug"]